# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99bab8129f87ad9494f08c642247b28523f2c7af8a93d0c4bbc6781c22569d3f0ca9c536574a45056fc901f078bea7b64ddf81476b7909293d8ee8a39d0e02ab

test:
  secret_key_base: 337626b3dd4c5d0e209083c20e71ecc3a0ace0769ca153fb52f706123d93400fc36e7475d61d4790d948345815fe0659b348bfe051228660e9af4746d4b014a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
